### ISSUE TITLE
Starting cellseeker error in terminal

### ISSUE THREAD

**Issue by jackcg** [SpirouLab/CellSeeker#2]
Hi all, 

I am receiving the error: 
File "cellseeker.py", line 153
    xold=self.emarray.shape[0]
                             ^
TabError: inconsistent use of tabs and spaces in indentation
after trying to run cellseeker with python cellseeker.py in terminal.

All necessary xcode. ImageMagick etc. installations have occurred properly.

Please help!

Cheers.

**Comment by TrystanMayfaire** [comment]
Hey, I'm going to look into this first thing Monday.  I'll get back to you ASAP.

**Comment by jackcg** [comment]
Awesome thanks!

Jack

On Aug 12, 2017 1:03 PM, "TrystanMayfaire" <notifications@github.com> wrote:

Hey, I'm going to look into this first thing Monday. I'll get back to you
ASAP.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SpirouLab/CellSeeker/issues/2#issuecomment-322002717>,
or mute the thread

**Comment by TrystanMayfaire** [comment]
Jack,

Error should be fixed now. Let me know if you have any more problems.

Paul
